apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: ${namespace}-output
  namespace: ${namespace}
spec:
  loki:
    configure_kubernetes_labels: true
    url: http://loki.cattle-logging-system.svc:3100
